import 'package:hive_flutter/hive_flutter.dart';
import '../models/gift.dart';

class GiftService {
  static final GiftService _instance = GiftService._internal();
  factory GiftService() => _instance;
  GiftService._internal();

  Box<Gift> get _giftBox => Hive.box<Gift>('gifts');

  Future<void> addGift(Gift gift) async {
    await _giftBox.put(gift.id, gift);
  }

  Future<void> updateGift(Gift gift) async {
    await _giftBox.put(gift.id, gift);
  }

  Future<void> deleteGift(String id) async {
    await _giftBox.delete(id);
  }

  List<Gift> getAllGifts() {
    return _giftBox.values.toList();
  }

  Gift? getGiftById(String id) {
    return _giftBox.get(id);
  }

  List<Gift> getGiftsByCategory(String category) {
    return _giftBox.values.where((gift) => gift.category == category).toList();
  }

  List<Gift> getGiftsByOccasion(String occasion) {
    return _giftBox.values
        .where((gift) => gift.occasions.contains(occasion))
        .toList();
  }

  List<Gift> getGiftsByPriceRange(double minPrice, double maxPrice) {
    return _giftBox.values
        .where((gift) => gift.price >= minPrice && gift.price <= maxPrice)
        .toList();
  }

  List<Gift> getGiftsByAvailability(bool isAvailable) {
    return _giftBox.values
        .where((gift) => gift.isAvailable == isAvailable)
        .toList();
  }

  List<Gift> getGiftsByAvailabilityType(String type) {
    return _giftBox.values
        .where((gift) => gift.availabilityType.toLowerCase() == type.toLowerCase())
        .toList();
  }

  List<Gift> getGiftsByInterests(List<String> interests) {
    return _giftBox.values
        .where((gift) =>
            gift.interests.any((interest) => interests.contains(interest)))
        .toList();
  }

  Future<void> seedInitialData() async {
    if (_giftBox.isEmpty) {
      // Home Decor Category Gifts
      final homeDecorGifts = [
        // Birthday Home Decor
        Gift(
          id: 'home_birthday_1',
          name: 'Personalized Wall Art',
          description: 'Custom wall art with personal message or photo',
          price: 49.99,
          category: 'Home Decor',
          occasions: ['Birthday'],
          interests: ['Art', 'Home Decor'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/home/personalized_wall_art.jpg',
        ),
        Gift(
          id: 'home_birthday_2',
          name: 'Decorative Throw Blanket',
          description: 'Soft and stylish throw blanket for comfort',
          price: 39.99,
          category: 'Home Decor',
          occasions: ['Birthday'],
          interests: ['Home Decor', 'Comfort'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/home/throw_blanket.jpg',
        ),
        Gift(
          id: 'home_birthday_3',
          name: 'Unique Candles',
          description: 'Set of decorative scented candles',
          price: 29.99,
          category: 'Home Decor',
          occasions: ['Birthday'],
          interests: ['Home Decor', 'Aromatherapy'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/home/candles.jpg',
        ),
        Gift(
          id: 'home_birthday_4',
          name: 'Photo Frame',
          description: 'Elegant photo frame for memories',
          price: 24.99,
          category: 'Home Decor',
          occasions: ['Birthday'],
          interests: ['Home Decor', 'Photography'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/home/photo_frame.jpg',
        ),
        Gift(
          id: 'home_birthday_5',
          name: 'Indoor Plant',
          description: 'Low-maintenance indoor plant with pot',
          price: 34.99,
          category: 'Home Decor',
          occasions: ['Birthday'],
          interests: ['Home Decor', 'Plants'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/home/indoor_plant.jpg',
        ),

        // Christmas Home Decor
        Gift(
          id: 'home_christmas_1',
          name: 'Christmas Tree Ornaments',
          description: 'Set of beautiful Christmas tree ornaments',
          price: 29.99,
          category: 'Home Decor',
          occasions: ['Christmas'],
          interests: ['Home Decor', 'Holidays'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/home/christmas_ornaments.jpg',
        ),
        Gift(
          id: 'home_christmas_2',
          name: 'Holiday-Themed Pillows',
          description: 'Festive decorative pillows for the season',
          price: 39.99,
          category: 'Home Decor',
          occasions: ['Christmas'],
          interests: ['Home Decor', 'Holidays'],
          availabilityType: 'In-store',
          isAvailable: false,
          imagePath: 'assets/images/home/holiday_pillows.jpg',
        ),
        Gift(
          id: 'home_christmas_3',
          name: 'Aromatic Candles',
          description: 'Holiday-scented decorative candles',
          price: 24.99,
          category: 'Home Decor',
          occasions: ['Christmas'],
          interests: ['Home Decor', 'Aromatherapy'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/home/holiday_candles.jpg',
        ),
        Gift(
          id: 'home_christmas_4',
          name: 'Fairy Lights',
          description: 'String of warm white fairy lights',
          price: 19.99,
          category: 'Home Decor',
          occasions: ['Christmas'],
          interests: ['Home Decor', 'Holidays'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/home/fairy_lights.jpg',
        ),
        Gift(
          id: 'home_christmas_5',
          name: 'Tabletop Christmas Tree',
          description: 'Mini decorative Christmas tree',
          price: 34.99,
          category: 'Home Decor',
          occasions: ['Christmas'],
          interests: ['Home Decor', 'Holidays'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/home/tabletop_tree.jpg',
        ),

        // Valentine's Day Home Decor
        Gift(
          id: 'home_valentine_1',
          name: 'Romantic Picture Frame',
          description: 'Heart-shaped picture frame for couples',
          price: 29.99,
          category: 'Home Decor',
          occasions: ['Valentine\'s Day'],
          interests: ['Home Decor', 'Romance'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/home/romantic_frame.jpg',
        ),
        Gift(
          id: 'home_valentine_2',
          name: 'Heart-Shaped Decorative Items',
          description: 'Set of heart-shaped decorative pieces',
          price: 24.99,
          category: 'Home Decor',
          occasions: ['Valentine\'s Day'],
          interests: ['Home Decor', 'Romance'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/home/heart_decor.jpg',
        ),
        Gift(
          id: 'home_valentine_3',
          name: 'Love-themed Wall Art',
          description: 'Romantic wall art with love quotes',
          price: 39.99,
          category: 'Home Decor',
          occasions: ['Valentine\'s Day'],
          interests: ['Home Decor', 'Romance'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/home/love_wall_art.jpg',
        ),
        Gift(
          id: 'home_valentine_4',
          name: 'Cozy Throw Blanket',
          description: 'Soft throw blanket with romantic design',
          price: 34.99,
          category: 'Home Decor',
          occasions: ['Valentine\'s Day'],
          interests: ['Home Decor', 'Comfort'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/home/romantic_blanket.jpg',
        ),
        Gift(
          id: 'home_valentine_5',
          name: 'Custom Couple\'s Mugs',
          description: 'Personalized mugs for couples',
          price: 29.99,
          category: 'Home Decor',
          occasions: ['Valentine\'s Day'],
          interests: ['Home Decor', 'Romance'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/home/couple_mugs.jpg',
        ),

        // Graduation Home Decor
        Gift(
          id: 'home_graduation_1',
          name: 'Inspirational Wall Art',
          description: 'Motivational wall art for graduates',
          price: 39.99,
          category: 'Home Decor',
          occasions: ['Graduation'],
          interests: ['Home Decor', 'Inspiration'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/home/inspirational_art.jpg',
        ),
        Gift(
          id: 'home_graduation_2',
          name: 'Desk Organizer Set',
          description: 'Professional desk organization set',
          price: 49.99,
          category: 'Home Decor',
          occasions: ['Graduation'],
          interests: ['Home Decor', 'Organization'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/home/desk_organizer.jpg',
        ),
        Gift(
          id: 'home_graduation_3',
          name: 'Personalized Sign',
          description: 'Custom graduation celebration sign',
          price: 34.99,
          category: 'Home Decor',
          occasions: ['Graduation'],
          interests: ['Home Decor', 'Personalization'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/home/graduation_sign.jpg',
        ),
        Gift(
          id: 'home_graduation_4',
          name: 'Graduation-Themed Candle',
          description: 'Scented candle with graduation theme',
          price: 24.99,
          category: 'Home Decor',
          occasions: ['Graduation'],
          interests: ['Home Decor', 'Aromatherapy'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/home/graduation_candle.jpg',
        ),
        Gift(
          id: 'home_graduation_5',
          name: 'Decorative Clock',
          description: 'Stylish wall clock for new graduates',
          price: 49.99,
          category: 'Home Decor',
          occasions: ['Graduation'],
          interests: ['Home Decor', 'Time Management'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/home/decorative_clock.jpg',
        ),
      ];

      for (final gift in homeDecorGifts) {
        await addGift(gift);
      }

      // Books Category Gifts
      final booksGifts = [
        // Birthday Books
        Gift(
          id: 'book_birthday_1',
          name: 'Bestselling Fiction Novel',
          description: 'A captivating fiction novel that will keep readers engaged',
          price: 24.99,
          category: 'Books',
          occasions: ['Birthday'],
          interests: ['Reading', 'Fiction'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/bestselling_novel.jpg',
        ),
        Gift(
          id: 'book_birthday_2',
          name: 'Personal Development Book',
          description: 'A book focused on personal growth and self-improvement',
          price: 19.99,
          category: 'Books',
          occasions: ['Birthday'],
          interests: ['Self-Improvement', 'Reading'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/personal_dev.jpg',
        ),
        Gift(
          id: 'book_birthday_3',
          name: 'Cookbook',
          description: 'A collection of delicious recipes for home cooking',
          price: 29.99,
          category: 'Books',
          occasions: ['Birthday'],
          interests: ['Cooking', 'Food'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/cookbook.jpg',
        ),
        Gift(
          id: 'book_birthday_4',
          name: 'Graphic Novel',
          description: 'An engaging graphic novel with stunning artwork',
          price: 34.99,
          category: 'Books',
          occasions: ['Birthday'],
          interests: ['Comics', 'Art'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/graphic_novel.jpg',
        ),
        Gift(
          id: 'book_birthday_5',
          name: 'Personalized Journal',
          description: 'A beautiful journal for writing thoughts and memories',
          price: 15.99,
          category: 'Books',
          occasions: ['Birthday'],
          interests: ['Writing', 'Stationery'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/journal.jpg',
        ),

        // Christmas Books
        Gift(
          id: 'book_christmas_1',
          name: 'Holiday-Themed Books',
          description: 'A collection of heartwarming holiday stories',
          price: 39.99,
          category: 'Books',
          occasions: ['Christmas'],
          interests: ['Reading', 'Holidays'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/holiday_stories.jpg',
        ),
        Gift(
          id: 'book_christmas_2',
          name: 'Coffee Table Book',
          description: 'A stunning coffee table book with beautiful photography',
          price: 49.99,
          category: 'Books',
          occasions: ['Christmas'],
          interests: ['Art', 'Photography'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/coffee_table.jpg',
        ),
        Gift(
          id: 'book_christmas_3',
          name: 'Poetry Book',
          description: 'A collection of inspiring poems',
          price: 19.99,
          category: 'Books',
          occasions: ['Christmas'],
          interests: ['Poetry', 'Literature'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/poetry.jpg',
        ),
        Gift(
          id: 'book_christmas_4',
          name: 'Holiday Cookbook',
          description: 'Recipes for festive meals and treats',
          price: 29.99,
          category: 'Books',
          occasions: ['Christmas'],
          interests: ['Cooking', 'Holidays'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/holiday_cookbook.jpg',
        ),
        Gift(
          id: 'book_christmas_5',
          name: 'Book Subscription Box',
          description: 'A monthly subscription for book lovers',
          price: 49.99,
          category: 'Books',
          occasions: ['Christmas'],
          interests: ['Reading', 'Subscription'],
          availabilityType: 'Online',
          isAvailable: false,
          imagePath: 'assets/images/books/subscription.jpg',
        ),

        // Valentine's Day Books
        Gift(
          id: 'book_valentine_1',
          name: 'Romantic Novel',
          description: 'A heartwarming love story',
          price: 24.99,
          category: 'Books',
          occasions: ['Valentine\'s Day'],
          interests: ['Romance', 'Fiction'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/romantic_novel.jpg',
        ),
        Gift(
          id: 'book_valentine_2',
          name: 'Personalized Love Story Book',
          description: 'A custom book featuring your love story',
          price: 39.99,
          category: 'Books',
          occasions: ['Valentine\'s Day'],
          interests: ['Romance', 'Personalization'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/love_story.jpg',
        ),
        Gift(
          id: 'book_valentine_3',
          name: 'Poetry Collection',
          description: 'A collection of romantic poems',
          price: 19.99,
          category: 'Books',
          occasions: ['Valentine\'s Day'],
          interests: ['Poetry', 'Romance'],
          availabilityType: 'Online',
          isAvailable: false,
          imagePath: 'assets/images/books/romantic_poetry.jpg',
        ),
        Gift(
          id: 'book_valentine_4',
          name: 'Love-Themed Coffee Table Book',
          description: 'A beautiful book celebrating love and relationships',
          price: 49.99,
          category: 'Books',
          occasions: ['Valentine\'s Day'],
          interests: ['Art', 'Romance'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/love_coffee_table.jpg',
        ),
        Gift(
          id: 'book_valentine_5',
          name: 'Couple\'s Recipe Book',
          description: 'A cookbook for romantic meals for two',
          price: 29.99,
          category: 'Books',
          occasions: ['Valentine\'s Day'],
          interests: ['Cooking', 'Romance'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/couple_recipes.jpg',
        ),

        // Graduation Books
        Gift(
          id: 'book_graduation_1',
          name: 'Motivational Books',
          description: 'Books to inspire and motivate',
          price: 24.99,
          category: 'Books',
          occasions: ['Graduation'],
          interests: ['Self-Improvement', 'Motivation'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/motivational.jpg',
        ),
        Gift(
          id: 'book_graduation_2',
          name: 'Career-Focused Books',
          description: 'Books to help with career development',
          price: 29.99,
          category: 'Books',
          occasions: ['Graduation'],
          interests: ['Career', 'Professional Development'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/career.jpg',
        ),
        Gift(
          id: 'book_graduation_3',
          name: 'Biography of a Role Model',
          description: 'An inspiring biography of a successful person',
          price: 34.99,
          category: 'Books',
          occasions: ['Graduation'],
          interests: ['Biography', 'Inspiration'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/biography.jpg',
        ),
        Gift(
          id: 'book_graduation_4',
          name: 'Travel Book',
          description: 'A guide to exploring the world',
          price: 39.99,
          category: 'Books',
          occasions: ['Graduation'],
          interests: ['Travel', 'Adventure'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/travel.jpg',
        ),
        Gift(
          id: 'book_graduation_5',
          name: 'Finance or Investment Book',
          description: 'A guide to managing money and investments',
          price: 29.99,
          category: 'Books',
          occasions: ['Graduation'],
          interests: ['Finance', 'Investment'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/books/finance.jpg',
        ),
      ];

      for (final gift in booksGifts) {
        await addGift(gift);
      }

      // Tech Category Gifts
      final techGifts = [
        // Birthday Tech
        Gift(
          id: 'tech_birthday_1',
          name: 'Smart Watch',
          description: 'Modern smartwatch with health tracking and notifications',
          price: 199.99,
          category: 'Tech',
          occasions: ['Birthday'],
          interests: ['Tech', 'Fitness'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/smartwatch.jpg',
        ),
        Gift(
          id: 'tech_birthday_2',
          name: 'Wireless Earbuds',
          description: 'High-quality wireless earbuds with noise cancellation',
          price: 149.99,
          category: 'Tech',
          occasions: ['Birthday'],
          interests: ['Tech', 'Music'],
          availabilityType: 'Online',
          isAvailable: false,
          imagePath: 'assets/images/tech/earbuds.jpg',
        ),
        Gift(
          id: 'tech_birthday_3',
          name: 'Smart Home Hub',
          description: 'Control your smart home devices with voice commands',
          price: 79.99,
          category: 'Tech',
          occasions: ['Birthday'],
          interests: ['Tech', 'Smart Home'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/smart_hub.jpg',
        ),
        Gift(
          id: 'tech_birthday_4',
          name: 'Portable Charger',
          description: 'High-capacity portable charger for all devices',
          price: 49.99,
          category: 'Tech',
          occasions: ['Birthday'],
          interests: ['Tech', 'Mobile'],
          availabilityType: 'In-store',
          isAvailable: false,
          imagePath: 'assets/images/tech/charger.jpg',
        ),
        Gift(
          id: 'tech_birthday_5',
          name: 'Smart Speaker',
          description: 'Voice-controlled smart speaker with premium sound',
          price: 99.99,
          category: 'Tech',
          occasions: ['Birthday'],
          interests: ['Tech', 'Music'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/speaker.jpg',
        ),

        // Christmas Tech
        Gift(
          id: 'tech_christmas_1',
          name: 'Smart TV',
          description: '4K Smart TV with streaming capabilities',
          price: 499.99,
          category: 'Tech',
          occasions: ['Christmas'],
          interests: ['Tech', 'Entertainment'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/tech/smart_tv.jpg',
        ),
        Gift(
          id: 'tech_christmas_2',
          name: 'Gaming Console',
          description: 'Latest gaming console with popular games',
          price: 399.99,
          category: 'Tech',
          occasions: ['Christmas'],
          interests: ['Tech', 'Gaming'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/tech/gaming_console.jpg',
        ),
        Gift(
          id: 'tech_christmas_3',
          name: 'Smart Thermostat',
          description: 'Energy-saving smart thermostat',
          price: 149.99,
          category: 'Tech',
          occasions: ['Christmas'],
          interests: ['Tech', 'Smart Home'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/thermostat.jpg',
        ),
        Gift(
          id: 'tech_christmas_4',
          name: 'Smart Security Camera',
          description: 'WiFi-enabled security camera with night vision',
          price: 79.99,
          category: 'Tech',
          occasions: ['Christmas'],
          interests: ['Tech', 'Security'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/security_camera.jpg',
        ),
        Gift(
          id: 'tech_christmas_5',
          name: 'Smart Doorbell',
          description: 'Video doorbell with motion detection',
          price: 129.99,
          category: 'Tech',
          occasions: ['Christmas'],
          interests: ['Tech', 'Security'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/doorbell.jpg',
        ),

        // Valentine's Day Tech
        Gift(
          id: 'tech_valentine_1',
          name: 'Smart Photo Frame',
          description: 'Digital photo frame for sharing memories',
          price: 89.99,
          category: 'Tech',
          occasions: ['Valentine\'s Day'],
          interests: ['Tech', 'Photography'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/photo_frame.jpg',
        ),
        Gift(
          id: 'tech_valentine_2',
          name: 'Smart Watch for Couples',
          description: 'Matching smartwatches for couples',
          price: 299.99,
          category: 'Tech',
          occasions: ['Valentine\'s Day'],
          interests: ['Tech', 'Fitness'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/couple_watch.jpg',
        ),
        Gift(
          id: 'tech_valentine_3',
          name: 'Smart LED Bulbs',
          description: 'Color-changing smart LED bulbs',
          price: 49.99,
          category: 'Tech',
          occasions: ['Valentine\'s Day'],
          interests: ['Tech', 'Smart Home'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/led_bulbs.jpg',
        ),
        Gift(
          id: 'tech_valentine_4',
          name: 'Smart Coffee Maker',
          description: 'Programmable smart coffee maker',
          price: 129.99,
          category: 'Tech',
          occasions: ['Valentine\'s Day'],
          interests: ['Tech', 'Coffee'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/coffee_maker.jpg',
        ),
        Gift(
          id: 'tech_valentine_5',
          name: 'Smart Scale',
          description: 'Smart body composition scale',
          price: 79.99,
          category: 'Tech',
          occasions: ['Valentine\'s Day'],
          interests: ['Tech', 'Fitness'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/scale.jpg',
        ),

        // Graduation Tech
        Gift(
          id: 'tech_graduation_1',
          name: 'Laptop',
          description: 'Powerful laptop for work and entertainment',
          price: 999.99,
          category: 'Tech',
          occasions: ['Graduation'],
          interests: ['Tech', 'Computers'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/laptop.jpg',
        ),
        Gift(
          id: 'tech_graduation_2',
          name: 'Professional Headphones',
          description: 'High-quality noise-canceling headphones',
          price: 199.99,
          category: 'Tech',
          occasions: ['Graduation'],
          interests: ['Tech', 'Music'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/headphones.jpg',
        ),
        Gift(
          id: 'tech_graduation_3',
          name: 'Smart Notebook',
          description: 'Digital notebook for note-taking',
          price: 149.99,
          category: 'Tech',
          occasions: ['Graduation'],
          interests: ['Tech', 'Productivity'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/smart_notebook.jpg',
        ),
        Gift(
          id: 'tech_graduation_4',
          name: 'Smart Backpack',
          description: 'USB-charging enabled smart backpack',
          price: 89.99,
          category: 'Tech',
          occasions: ['Graduation'],
          interests: ['Tech', 'Travel'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/smart_backpack.jpg',
        ),
        Gift(
          id: 'tech_graduation_5',
          name: 'Smart Desk',
          description: 'Adjustable standing desk with USB ports',
          price: 299.99,
          category: 'Tech',
          occasions: ['Graduation'],
          interests: ['Tech', 'Productivity'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/tech/smart_desk.jpg',
        ),
      ];

      for (final gift in techGifts) {
        await addGift(gift);
      }

      // Fashion Category Gifts
      final fashionGifts = [
        // Birthday Fashion
        Gift(
          id: 'fashion_birthday_1',
          name: 'Designer Watch',
          description: 'Elegant timepiece with leather strap',
          price: 199.99,
          category: 'Fashion',
          occasions: ['Birthday'],
          interests: ['Fashion', 'Accessories'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/watch.jpg',
        ),
        Gift(
          id: 'fashion_birthday_2',
          name: 'Leather Wallet',
          description: 'Genuine leather wallet with multiple card slots',
          price: 49.99,
          category: 'Fashion',
          occasions: ['Birthday'],
          interests: ['Fashion', 'Accessories'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/wallet.jpg',
        ),
        Gift(
          id: 'fashion_birthday_3',
          name: 'Designer Sunglasses',
          description: 'Stylish sunglasses with UV protection',
          price: 129.99,
          category: 'Fashion',
          occasions: ['Birthday'],
          interests: ['Fashion', 'Accessories'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/sunglasses.jpg',
        ),
        Gift(
          id: 'fashion_birthday_4',
          name: 'Silk Scarf',
          description: 'Beautiful silk scarf with unique pattern',
          price: 59.99,
          category: 'Fashion',
          occasions: ['Birthday'],
          interests: ['Fashion', 'Accessories'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/scarf.jpg',
        ),
        Gift(
          id: 'fashion_birthday_5',
          name: 'Leather Belt',
          description: 'Classic leather belt with adjustable buckle',
          price: 39.99,
          category: 'Fashion',
          occasions: ['Birthday'],
          interests: ['Fashion', 'Accessories'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/belt.jpg',
        ),

        // Christmas Fashion
        Gift(
          id: 'fashion_christmas_1',
          name: 'Winter Scarf',
          description: 'Warm and stylish winter scarf',
          price: 34.99,
          category: 'Fashion',
          occasions: ['Christmas'],
          interests: ['Fashion', 'Accessories'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/fashion/winter_scarf.jpg',
        ),
        Gift(
          id: 'fashion_christmas_2',
          name: 'Designer Gloves',
          description: 'Luxury leather gloves for winter',
          price: 79.99,
          category: 'Fashion',
          occasions: ['Christmas'],
          interests: ['Fashion', 'Accessories'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/gloves.jpg',
        ),
        Gift(
          id: 'fashion_christmas_3',
          name: 'Holiday Sweater',
          description: 'Festive holiday-themed sweater',
          price: 59.99,
          category: 'Fashion',
          occasions: ['Christmas'],
          interests: ['Fashion', 'Holidays'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/fashion/holiday_sweater.jpg',
        ),
        Gift(
          id: 'fashion_christmas_4',
          name: 'Winter Boots',
          description: 'Stylish and warm winter boots',
          price: 129.99,
          category: 'Fashion',
          occasions: ['Christmas'],
          interests: ['Fashion', 'Shoes'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/winter_boots.jpg',
        ),
        Gift(
          id: 'fashion_christmas_5',
          name: 'Holiday Accessories Set',
          description: 'Set of festive holiday accessories',
          price: 49.99,
          category: 'Fashion',
          occasions: ['Christmas'],
          interests: ['Fashion', 'Holidays'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/holiday_accessories.jpg',
        ),

        // Valentine's Day Fashion
        Gift(
          id: 'fashion_valentine_1',
          name: 'Romantic Jewelry Set',
          description: 'Elegant jewelry set with romantic theme',
          price: 89.99,
          category: 'Fashion',
          occasions: ['Valentine\'s Day'],
          interests: ['Fashion', 'Jewelry'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/romantic_jewelry.jpg',
        ),
        Gift(
          id: 'fashion_valentine_2',
          name: 'Heart Necklace',
          description: 'Delicate heart-shaped necklace',
          price: 69.99,
          category: 'Fashion',
          occasions: ['Valentine\'s Day'],
          interests: ['Fashion', 'Jewelry'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/fashion/heart_necklace.jpg',
        ),
        Gift(
          id: 'fashion_valentine_3',
          name: 'Romantic Perfume',
          description: 'Luxury perfume with romantic scent',
          price: 79.99,
          category: 'Fashion',
          occasions: ['Valentine\'s Day'],
          interests: ['Fashion', 'Beauty'],
          availabilityType: 'In-store',
          isAvailable: false,
          imagePath: 'assets/images/fashion/romantic_perfume.jpg',
        ),
        Gift(
          id: 'fashion_valentine_4',
          name: 'Couple\'s Watch Set',
          description: 'Matching watches for couples',
          price: 199.99,
          category: 'Fashion',
          occasions: ['Valentine\'s Day'],
          interests: ['Fashion', 'Accessories'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/couple_watches.jpg',
        ),
        Gift(
          id: 'fashion_valentine_5',
          name: 'Romantic Handbag',
          description: 'Stylish handbag with romantic design',
          price: 129.99,
          category: 'Fashion',
          occasions: ['Valentine\'s Day'],
          interests: ['Fashion', 'Accessories'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/romantic_bag.jpg',
        ),

        // Graduation Fashion
        Gift(
          id: 'fashion_graduation_1',
          name: 'Professional Watch',
          description: 'Classic watch suitable for professional settings',
          price: 149.99,
          category: 'Fashion',
          occasions: ['Graduation'],
          interests: ['Fashion', 'Accessories'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/fashion/professional_watch.jpg',
        ),
        Gift(
          id: 'fashion_graduation_2',
          name: 'Business Attire Set',
          description: 'Professional clothing set for work',
          price: 199.99,
          category: 'Fashion',
          occasions: ['Graduation'],
          interests: ['Fashion', 'Professional'],
          availabilityType: 'In-store',
          isAvailable: false,
          imagePath: 'assets/images/fashion/business_attire.jpg',
        ),
        Gift(
          id: 'fashion_graduation_3',
          name: 'Professional Bag',
          description: 'Stylish briefcase or laptop bag',
          price: 89.99,
          category: 'Fashion',
          occasions: ['Graduation'],
          interests: ['Fashion', 'Professional'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/fashion/professional_bag.jpg',
        ),
        Gift(
          id: 'fashion_graduation_4',
          name: 'Classic Jewelry Set',
          description: 'Professional jewelry set for work',
          price: 79.99,
          category: 'Fashion',
          occasions: ['Graduation'],
          interests: ['Fashion', 'Jewelry'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/fashion/classic_jewelry.jpg',
        ),
        Gift(
          id: 'fashion_graduation_5',
          name: 'Professional Shoes',
          description: 'Comfortable and stylish work shoes',
          price: 129.99,
          category: 'Fashion',
          occasions: ['Graduation'],
          interests: ['Fashion', 'Shoes'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/fashion/professional_shoes.jpg',
        ),
      ];

      for (final gift in fashionGifts) {
        await addGift(gift);
      }

      // Sports Category Gifts
      final sportsGifts = [
        // Birthday Sports
        Gift(
          id: 'sports_birthday_1',
          name: 'Yoga Mat',
          description: 'Premium non-slip yoga mat',
          price: 29.99,
          category: 'Sports',
          occasions: ['Birthday'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/sports/yoga_mat.jpg',
        ),
        Gift(
          id: 'sports_birthday_2',
          name: 'Running Shoes',
          description: 'Comfortable running shoes with cushioning',
          price: 89.99,
          category: 'Sports',
          occasions: ['Birthday'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/sports/running_shoes.jpg',
        ),
        Gift(
          id: 'sports_birthday_3',
          name: 'Sports Watch',
          description: 'Water-resistant sports watch with tracking',
          price: 79.99,
          category: 'Sports',
          occasions: ['Birthday'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/sports/sports_watch.jpg',
        ),
        Gift(
          id: 'sports_birthday_4',
          name: 'Gym Bag',
          description: 'Spacious gym bag with compartments',
          price: 39.99,
          category: 'Sports',
          occasions: ['Birthday'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/sports/gym_bag.jpg',
        ),
        Gift(
          id: 'sports_birthday_5',
          name: 'Resistance Bands',
          description: 'Set of resistance bands for workouts',
          price: 24.99,
          category: 'Sports',
          occasions: ['Birthday'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/sports/resistance_bands.jpg',
        ),

        // Christmas Sports
        Gift(
          id: 'sports_christmas_1',
          name: 'Winter Sports Gear',
          description: 'Complete winter sports equipment set',
          price: 199.99,
          category: 'Sports',
          occasions: ['Christmas'],
          interests: ['Sports', 'Winter'],
          availabilityType: 'In-store',
          isAvailable: false,
          imagePath: 'assets/images/sports/winter_gear.jpg',
        ),
        Gift(
          id: 'sports_christmas_2',
          name: 'Sports Equipment Set',
          description: 'Set of essential sports equipment',
          price: 149.99,
          category: 'Sports',
          occasions: ['Christmas'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/sports/equipment_set.jpg',
        ),
        Gift(
          id: 'sports_christmas_3',
          name: 'Sports Apparel Set',
          description: 'Complete set of sports clothing',
          price: 89.99,
          category: 'Sports',
          occasions: ['Christmas'],
          interests: ['Sports', 'Fashion'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/sports/apparel_set.jpg',
        ),
        Gift(
          id: 'sports_christmas_4',
          name: 'Sports Nutrition Kit',
          description: 'Complete sports nutrition package',
          price: 79.99,
          category: 'Sports',
          occasions: ['Christmas'],
          interests: ['Sports', 'Nutrition'],
          availabilityType: 'In-store',
          isAvailable: false,
          imagePath: 'assets/images/sports/nutrition_kit.jpg',
        ),
        Gift(
          id: 'sports_christmas_5',
          name: 'Sports Recovery Kit',
          description: 'Complete sports recovery equipment set',
          price: 69.99,
          category: 'Sports',
          occasions: ['Christmas'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/sports/recovery_kit.jpg',
        ),

        // Valentine's Day Sports
        Gift(
          id: 'sports_valentine_1',
          name: 'Couple\'s Yoga Set',
          description: 'Matching yoga mats and accessories for couples',
          price: 89.99,
          category: 'Sports',
          occasions: ['Valentine\'s Day'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/sports/couple_yoga.jpg',
        ),
        Gift(
          id: 'sports_valentine_2',
          name: 'Partner Workout Kit',
          description: 'Equipment for partner exercises',
          price: 79.99,
          category: 'Sports',
          occasions: ['Valentine\'s Day'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/sports/partner_workout.jpg',
        ),
        Gift(
          id: 'sports_valentine_3',
          name: 'Couple\'s Sports Watch Set',
          description: 'Matching sports watches for couples',
          price: 199.99,
          category: 'Sports',
          occasions: ['Valentine\'s Day'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/sports/couple_watches.jpg',
        ),
        Gift(
          id: 'sports_valentine_4',
          name: 'Romantic Sports Gear',
          description: 'Sports equipment with romantic design',
          price: 69.99,
          category: 'Sports',
          occasions: ['Valentine\'s Day'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/sports/romantic_gear.jpg',
        ),
        Gift(
          id: 'sports_valentine_5',
          name: 'Couple\'s Fitness Tracker',
          description: 'Matching fitness trackers for couples',
          price: 149.99,
          category: 'Sports',
          occasions: ['Valentine\'s Day'],
          interests: ['Sports', 'Fitness'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/sports/couple_trackers.jpg',
        ),

        // Graduation Sports
        Gift(
          id: 'sports_graduation_1',
          name: 'Professional Sports Bag',
          description: 'High-quality sports bag for professionals',
          price: 89.99,
          category: 'Sports',
          occasions: ['Graduation'],
          interests: ['Sports', 'Professional'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/sports/pro_bag.jpg',
        ),
        Gift(
          id: 'sports_graduation_2',
          name: 'Advanced Sports Equipment',
          description: 'Professional-grade sports equipment',
          price: 199.99,
          category: 'Sports',
          occasions: ['Graduation'],
          interests: ['Sports', 'Professional'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/sports/pro_equipment.jpg',
        ),
        Gift(
          id: 'sports_graduation_3',
          name: 'Sports Nutrition Guide',
          description: 'Professional sports nutrition guide',
          price: 49.99,
          category: 'Sports',
          occasions: ['Graduation'],
          interests: ['Sports', 'Nutrition'],
          availabilityType: 'In-store',
          isAvailable: true,
          imagePath: 'assets/images/sports/nutrition_guide.jpg',
        ),
        Gift(
          id: 'sports_graduation_4',
          name: 'Professional Sports Watch',
          description: 'Advanced sports watch with tracking',
          price: 299.99,
          category: 'Sports',
          occasions: ['Graduation'],
          interests: ['Sports', 'Professional'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/sports/pro_watch.jpg',
        ),
        Gift(
          id: 'sports_graduation_5',
          name: 'Sports Recovery System',
          description: 'Professional sports recovery equipment',
          price: 149.99,
          category: 'Sports',
          occasions: ['Graduation'],
          interests: ['Sports', 'Professional'],
          availabilityType: 'Online',
          isAvailable: true,
          imagePath: 'assets/images/sports/recovery_system.jpg',
        ),
      ];

      for (final gift in sportsGifts) {
        await addGift(gift);
      }
    }
  }
}